apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter3
  labels:
    app: node-exporter3
spec:
  selector:
    matchLabels:
      app: node-exporter3
  template:
    metadata:
      labels:
        app: node-exporter3
      name: node-exporter3
    spec:
      containers:
      - image: prom/node-exporter
        name: node-exporter3
        ports:
        - containerPort: 9200
          hostPort: 9200
          name: scrape
        volumeMounts:
        - name: data-disk
          mountPath: /data-disk
          readOnly: true
        - name: root-disk
          mountPath: /root-disk
          readOnly: true
      volumes:
        - name: data-disk
          hostPath:
            path: /localdata
        - name: root-disk
          hostPath:
            path: /
      hostNetwork: true
      hostPID: true

